### ISSUE TITLE
I can't get any of these to work.

### ISSUE THREAD

**Issue by geoidesic** [cboden/Ratchet-examples#12]
The instructions in your readme are a bit scarce! :)

After cloning and running composer I'm getting all sorts of errors. E.g:

PHP Fatal error:  Class 'React\ZMQ\Context' not found in /Users/noeldacosta/Documents/NOEL/htdocs/test-dev/ratchet/tutorial/bin/website-chatroom.php on line 39

Fatal error: Interface 'Ratchet\Wamp\WampServerInterface' not found in /Users/noeldacosta/Documents/NOEL/htdocs/test-dev/ratchet/tutorial/src/Website/ChatRoom.php on line 6

I'm lost at sea...

**Comment by cboden** [comment]
My apologies for the lack of documentation; this was just meant as a couple working examples based on the documentation from the website. I just did the following set of commands to get one of the examples working:
```bash
git clone https://github.com/cboden/Ratchet-examples
cd Ratchet-examples
composer install
php bin/tutorial-terminal-chat.php
```

**Comment by M1ke** [comment]
You need to install Zero MQ:

* http://zeromq.org/intro:get-the-software#toc6 and follow the instructions inside (up to `sudo ldconfig`)
* `sudo pecl install channel://pecl.php.net/zmq-1.1.2`
* `sudo php5enmod zmq`

Then in your directory for the examples:

* `composer require "react/zmq" "0.2.*|0.3.*"`

You might also experience issues from ports already in use, eg. 80 will be used by Apache.
