### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by alexolliveira** [cboden/Ratchet-examples#18]
WebSocket connection to 'ws://127.0.0.1:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by cboden** [comment]
I see you've opened issues on 6 WebSocket repositories with pretty much the same error message. 

Please follow documentation to the best of your ability. If you're still unable to resolve your issue please provide more context and steps to reproduce the issue you're having. 

Based on all the error messages you've copy/pasted it looks like the service you're trying to connect to isn't running.
